version: 2
jobs:
  build:
    docker:
      - image: circleci/node:13-browsers
    steps:
      - checkout
      - run: mkdir reports
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}
          - v2-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - run:
          name: Start Selenium
          command: |
            java -jar node_modules/selenium-server-standalone/index.jar -log reports/selenium.log
          background: true
      - run:
          name: Create a production build
          command: |
            yarn build
      - run:
          name: Run server
          command: |
            yarn serve
          background: true
      - run:
          name: Wait for server
          command: yarn wait-on http://localhost:3000 -t 10000
      - run: yarn test --testPathIgnorePatterns src/shared/OpenFiscaAPIClient/OpenFiscaAPIClient.test.js
      - store_artifacts:
          path: ./reports/failure_screenshots/
